name: NASA PROJECT CI
on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]
jobs:
  build:
    runs-on: ubuntu-latest
    env: 
      CI: true
    strategy:
      matrix:
        node-versions: [18.x, 20.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js version ${{matrix.node-version}}
        uses: actions/setup-node@v3
        with:  
          node-version: ${{matrix.node-version}}
      - run: npm install
      - run: npm run build --prefix client
      - run: npm test